#!/bin/sh
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>
# K-3D Modifications: Timothy M. Shead <tshead@k-3d.com>

BUNDLE="`echo "$0" | sed -e 's/\/Contents\/MacOS\/K-3D//'`"
RESOURCES="$BUNDLE/Contents/Resources"
COMMAND_LINE="\"$RESOURCES/bin/k3d\" \"--plugins=$RESOURCES/lib/k3d/plugins\" \"--share=$RESOURCES/share\" \"--ui=$RESOURCES/lib/k3d/uiplugins/k3d-ngui.module\""

echo "running $0"
echo "BUNDLE: $BUNDLE"
echo "RESOURCES: $RESOURCES"
echo "COMMAND_LINE: $COMMAND_LINE"

ps -wx -ocommand | grep -e '[X]11' > /dev/null
if [ "$?" != "0" -a ! -f ~/.xinitrc ]; then
    echo "rm -f ~/.xinitrc" > ~/.xinitrc
    sed 's/xterm/# xterm/' /usr/X11R6/lib/X11/xinit/xinitrc >> ~/.xinitrc
fi

cp -f "$RESOURCES/bin/getdisplay.sh" /tmp/
rm -f /tmp/display.$UID
open-x11 /tmp/getdisplay.sh || \
open -a XDarwin /tmp/getdisplay.sh || \
echo ":0" > /tmp/display.$UID

while [ "$?" == "0" -a ! -f /tmp/display.$UID ]; do
    sleep 1
done
export DISPLAY="`cat /tmp/display.$UID`"

ps -wx -ocommand | grep -e '[X]11' > /dev/null || exit 11

export DYLD_LIBRARY_PATH="$RESOURCES/lib"
export PATH="$RESOURCES/bin:$PATH"
exec "$RESOURCES/bin/k3d" "--log-level=debug" "--plugins=$RESOURCES/lib/k3d/plugins" "--share=$RESOURCES/share" "--ui=$RESOURCES/lib/k3d/uiplugins/k3d-ngui.module"

