#!/bin/sh
#
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>
# K-3D Modifications: Timothy M. Shead <tshead@k-3d.com>

BUNDLE="`echo "$0" | sed -e 's/\/Contents\/Resources\/startup-script//'`"
PREFIX="`echo "$0" | sed -e 's/\/startup-script//'`"

echo "running $0"
echo "BUNDLE: $BUNDLE"
echo "PREFIX: $PREFIX"

cd "$BUNDLE"
exec "$PREFIX/bin/k3d-startup" "$@"

