#python

import k3d

module_contents = ['__doc__', '__name__', 'angle_axis', 'angle_order', 'attribute_arrays', 'batch_mode', 'bicubic_patches', 'bilinear_patches', 'bitmap', 'blobbies', 'bounding_box3', 'check_node_environment', 'close_document', 'color', 'command_nodes', 'component_deselect_all', 'component_select_all', 'const_attribute_arrays', 'const_bicubic_patches', 'const_bilinear_patches', 'const_bitmap', 'const_blobbies', 'const_cubic_curve_groups', 'const_k3d_bool_t_array', 'const_k3d_color_array', 'const_k3d_double_t_array', 'const_k3d_imaterial_array', 'const_k3d_inode_array', 'const_k3d_int16_t_array', 'const_k3d_int32_t_array', 'const_k3d_int64_t_array', 'const_k3d_int8_t_array', 'const_k3d_matrix4_array', 'const_k3d_mesh_blobbies_t_operator_type_array', 'const_k3d_mesh_blobbies_t_primitive_type_array', 'const_k3d_mesh_polyhedra_t_polyhedron_type_array', 'const_k3d_normal3_array', 'const_k3d_point2_array', 'const_k3d_point3_array', 'const_k3d_point4_array', 'const_k3d_string_t_array', 'const_k3d_texture3_array', 'const_k3d_uint16_t_array', 'const_k3d_uint32_t_array', 'const_k3d_uint64_t_array', 'const_k3d_uint8_t_array', 'const_k3d_vector2_array', 'const_k3d_vector3_array', 'const_linear_curve_groups', 'const_nurbs_curve_groups', 'const_nurbs_patches', 'const_point_groups', 'const_polyhedra', 'create_plugin', 'cubic_curve_groups', 'deselect_all', 'documents', 'dynamic_cast', 'euler', 'euler_angles', 'execute_script', 'exit', 'generic_path', 'get_command_node', 'icommand_node', 'identity3', 'idocument', 'imaterial', 'imesh_storage', 'imetadata', 'inode', 'inode_selection', 'intersect_lines', 'iplugin_factory', 'iproperty', 'iproperty_collection', 'is_solid', 'is_triangles', 'is_uninitialized', 'isnappable', 'iunknown', 'iuser_interface', 'k3d_bool_t_array', 'k3d_color_array', 'k3d_double_t_array', 'k3d_imaterial_array', 'k3d_inode_array', 'k3d_int16_t_array', 'k3d_int32_t_array', 'k3d_int64_t_array', 'k3d_int8_t_array', 'k3d_matrix4_array', 'k3d_mesh_blobbies_t_operator_type_array', 'k3d_mesh_blobbies_t_primitive_type_array', 'k3d_mesh_polyheda_t_polyhedron_type_array', 'k3d_normal3_array', 'k3d_point2_array', 'k3d_point3_array', 'k3d_point4_array', 'k3d_string_t_array', 'k3d_texture3_array', 'k3d_uint16_t_array', 'k3d_uint32_t_array', 'k3d_uint64_t_array', 'k3d_uint8_t_array', 'k3d_vector2_array', 'k3d_vector3_array', 'length', 'linear_curve_groups', 'log', 'log_critical', 'log_debug', 'log_error', 'log_info', 'log_warning', 'matrix4', 'mesh', 'mesh_selection', 'mime', 'native_path', 'new_document', 'node', 'normal3', 'nurbs_curve_groups', 'nurbs_patches', 'open_document', 'operator_type', 'parallel', 'path', 'plugin', 'plugins', 'point2', 'point3', 'point4', 'point_groups', 'polyhedra', 'polyhedron_type', 'primitive_type', 'print_diff', 'resource', 'ri_render_state', 'rotate3', 'scale3', 'select_all', 'select_null', 'share_path', 'texture3', 'to_vector3', 'translate3', 'ui', 'uuid', 'validate', 'vector3']

if dir(k3d) != module_contents:
	raise "Python module 'k3d' contents changed unexpectedly"

