SET(K3D_CGAL_FOUND 0)

FIND_PATH(K3D_CGAL_INCLUDE_DIR CGAL
	/usr/include
	/usr/local/include 
	DOC "Directory where the CGAL header directory is located"
	)
MARK_AS_ADVANCED(K3D_CGAL_INCLUDE_DIR)

FIND_LIBRARY(K3D_CGAL_LIBRARY CGAL
	DOC "The CGAL library"
	)
MARK_AS_ADVANCED(K3D_CGAL_LIBRARY)

IF(K3D_CGAL_INCLUDE_DIR AND K3D_CGAL_LIBRARY)
	SET(K3D_CGAL_FOUND 1)
ENDIF(K3D_CGAL_INCLUDE_DIR AND K3D_CGAL_LIBRARY)

