FIND_PATH(K3D_UUID_INCLUDE_DIR uuid/uuid.h
	/usr/include
	DOC "Directory where the uuid header files are located"
	)
MARK_AS_ADVANCED(K3D_UUID_INCLUDE_DIR)

SET(K3D_UUID_LIB uuid CACHE STRING "")
MARK_AS_ADVANCED(K3D_UUID_LIB)

SET(K3D_UUID_INCLUDE_DIRS
	${K3D_UUID_INCLUDE_DIR}
	)

SET(K3D_UUID_LIBS
	${K3D_UUID_LIB}
	)

SET(K3D_UUID_FOUND 1)

