SET(K3D_GTKSOURCEVIEW_FOUND 0)

INCLUDE(K3DFindPkgConfig)
PKG_CHECK_MODULES(GTKSOURCEVIEW gtksourceview-2.0)

IF(GTKSOURCEVIEW_FOUND)
	SET(K3D_GTKSOURCEVIEW_INCLUDE_DIRS
		${GTKSOURCEVIEW_INCLUDE_DIRS}
		)

	SET(K3D_GTKSOURCEVIEW_LIBRARY_DIRS
		${GTKSOURCEVIEW_LIBRARY_DIRS}
		)

	SET(K3D_GTKSOURCEVIEW_LIBRARIES
		${GTKSOURCEVIEW_LIBRARIES}
		)

	SET(K3D_GTKSOURCEVIEW_FOUND 1)
ENDIF(GTKSOURCEVIEW_FOUND)

