SET(K3D_IMAGEMAGICK_FOUND 0)

find_package(ImageMagick COMPONENTS Magick++)

IF(ImageMagick_FOUND)
	SET(K3D_IMAGEMAGICK_INCLUDE_DIRS
		${ImageMagick_INCLUDE_DIRS}
		)

	SET(K3D_IMAGEMAGICK_LIBS
		${ImageMagick_LIBRARIES}
		)

	SET(K3D_IMAGEMAGICK_FOUND 1)
ENDIF(ImageMagick_FOUND)

