SET(K3D_SUPERLU_FOUND 0)

#note: Include files are assumed to be in the standard include path, in the superlu dir

FIND_LIBRARY(K3D_SUPERLU_LIBRARY superlu
	DOC "The SuperLU library"
	)
MARK_AS_ADVANCED(K3D_SUPERLU_LIBRARY)

FIND_LIBRARY(K3D_BLAS_LIBRARY blas
	DOC "The BLAS library used by SuperLU"
	)
MARK_AS_ADVANCED(K3D_BLAS_LIBRARY)

IF(K3D_SUPERLU_LIBRARY AND K3D_BLAS_LIBRARY)
	SET(K3D_SUPERLU_FOUND 1)
ENDIF(K3D_SUPERLU_LIBRARY AND K3D_BLAS_LIBRARY)
