SET(K3D_XML_FOUND)

ADD_DEFINITIONS(-DK3D_HAVE_EXPAT)
FIND_PATH(K3D_XML_INCLUDE_DIR expat.h
	/usr/include
	DOC "Directory where the expat header files are located"
	)
MARK_AS_ADVANCED(K3D_XML_INCLUDE_DIR)

SET(K3D_XML_LIB expat CACHE STRING "")
MARK_AS_ADVANCED(K3D_XML_LIB)

SET(K3D_XML_FOUND 1)
