SET(K3D_CAIROMM_FOUND 0)

INCLUDE(K3DFindPkgConfig)
PKG_CHECK_MODULES(CAIROMM cairomm-1.0)

IF(CAIROMM_FOUND)
	SET(K3D_CAIROMM_INCLUDE_DIRS
		${CAIROMM_INCLUDE_DIRS}
		)

	SET(K3D_CAIROMM_LIB_DIRS
		${CAIROMM_LIBRARY_DIRS}
		)

	SET(K3D_CAIROMM_LIBS
		${CAIROMM_LIBRARIES}
		)

	SET(K3D_CAIROMM_FOUND 1)
ENDIF(CAIROMM_FOUND)

