SET(K3D_OPENGL_FOUND 0)

FIND_PACKAGE(OpenGL)

FIND_LIBRARY(K3D_GLEW_LIBRARY NAMES GLEWmx GLEW
	DOC "The Glew shared library file"
)

FIND_PATH(K3D_GLEW_INCLUDE_DIR GL/glew.h ${OPENGL_INCLUDE_DIR})

IF(OPENGL_FOUND AND OPENGL_GLU_FOUND AND K3D_GLEW_LIBRARY AND K3D_GLEW_INCLUDE_DIR)
  SET(K3D_OPENGL_INCLUDE_DIR ${OPENGL_INCLUDE_DIR} ${K3D_GLEW_INCLUDE_DIR})
  SET(K3D_OPENGL_LIBRARIES ${K3D_GLEW_LIBRARY} ${OPENGL_LIBRARIES})
  SET(K3D_OPENGL_FOUND 1)
ENDIF()

