SET(K3D_GLIBMM_FOUND 0)

INCLUDE(K3DFindPkgConfig)
PKG_CHECK_MODULES(GLIBMM glibmm-2.4)

IF(GLIBMM_FOUND)
	SET(K3D_GLIBMM_INCLUDE_DIRS
		${GLIBMM_INCLUDE_DIRS}
		)

	SET(K3D_GLIBMM_LIB_DIRS
		${GLIBMM_LIBRARY_DIRS}
		)

	SET(K3D_GLIBMM_LIBS
		${GLIBMM_LIBRARIES}
		)

	SET(K3D_GLIBMM_FOUND 1)
ENDIF(GLIBMM_FOUND)

