SET(K3D_BOOST_INCLUDE_DIR "" CACHE PATH "Override the default location for Boost header files.")
SET(K3D_BOOST_LIBRARY_DIR "" CACHE PATH "Override the default location for Boost libraries.")
SET(K3D_BOOST_USE_MULTITHREADED OFF CACHE BOOL "Use multithreaded Boost libraries.")

SET(BOOST_INCLUDEDIR ${K3D_BOOST_INCLUDE_DIR})
SET(BOOST_LIBRARYDIR ${K3D_BOOST_LIBRARY_DIR})
SET(Boost_ADDITIONAL_VERSIONS 1.43 1.43.0)
SET(Boost_USE_MULTITHREADED ${K3D_BOOST_USE_MULTITHREADED})
FIND_PACKAGE(Boost 1.42 COMPONENTS ${K3D_BOOST_COMPONENTS} REQUIRED)

