SET(K3D_FTGL_FOUND 0)

FIND_PATH(K3D_FTGL_INCLUDE_DIR FTGL/ftgl.h
	DOC "Directory where the FTGL directory, containing the ftgl headers, is located"
	)
MARK_AS_ADVANCED(K3D_FTGL_INCLUDE_DIR)

FIND_LIBRARY(K3D_FTGL_LIBRARY ftgl
	DOC "The FTGL library"
	)
MARK_AS_ADVANCED(K3D_FTGL_LIBRARY)

IF(K3D_FTGL_INCLUDE_DIR AND K3D_FTGL_LIBRARY)
	SET(K3D_FTGL_FOUND 1)
ENDIF()

