SET(K3D_PYTHON_FOUND 0)

INCLUDE(FindPythonLibs)

IF(PYTHONLIBS_FOUND)
	SET(K3D_PYTHON_INCLUDE_DIRS
		${PYTHON_INCLUDE_PATH}
		)

	SET(K3D_PYTHON_LIBS
		${PYTHON_LIBRARY}
		)

	SET(K3D_PYTHON_FOUND 1)
ENDIF()

MARK_AS_ADVANCED(PYTHON_INCLUDE_PATH)
MARK_AS_ADVANCED(PYTHON_LIBRARY)
MARK_AS_ADVANCED(PYTHON_DEBUG_LIBRARIES)
MARK_AS_ADVANCED(PY_MODULES_LIST)
MARK_AS_ADVANCED(PY_STATIC_MODULES_LIST)

