# Compiler configuration
IF(WIN32)
	IF(MSVC)
		SET(K3D_COMPILER_MSVC TRUE)
	ELSE(MSVC)
		SET(K3D_COMPILER_GCC TRUE)
	ENDIF(MSVC)
ELSE(WIN32)
	SET(K3D_COMPILER_GCC TRUE)
ENDIF(WIN32)

# Processor configuration
SET(K3D_PROCESSOR ${CMAKE_SYSTEM_PROCESSOR})
IF(CMAKE_SYSTEM_PROCESSOR STREQUAL "i386")
  SET(K3D_PROCESSOR_386 TRUE)
ELSEIF(CMAKE_SYSTEM_PROCESSOR STREQUAL "i686")
  SET(K3D_PROCESSOR_686 TRUE)
ENDIF()

# Win32 API configuration
IF(WIN32)
	SET(K3D_API_WIN32 TRUE)
ENDIF(WIN32)

# Darwin API configuration
IF(APPLE)
	SET(K3D_API_DARWIN TRUE)
ENDIF(APPLE)

